import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from "react";
import 'react-phone-number-input/style.css'
import PhoneInput from 'react-phone-number-input'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [step, setStep] = useState(0);
  const [selectedClothes, setSelectedClothes] = useState([]);
  const [zipCode, setZipCode] = useState("");
  const [zipCodeState, setZipCodeState] = useState("");

  const [phone, setPhone] = useState("");
  var zipcodes = require('zipcodes');

  return (
    <>
      <Head>
        <title>Aurora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          

              <main style={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100vh", width: "100vw", margin: -8}}>
              <div style={{backgroundColor: "#fff", width: "fit-content", padding: 8, borderRadius: 16, margin: "auto"}}>
                <div>
                  <h1 style={{margin: 0}}>Aurora</h1>
                  <p>Morning mobile notifications to let you know what<br/> clothes to wear based on the weather in your zip code</p>
                  
                </div>
          
            <div>
              <p>What's your Zipcode?</p>
              <input type="zipcode" placeholder="Zip Code" value={zipCode} onChange={event => {
                setZipCode(event.target.value)
                if(zipcodes.lookup(event.target.value) != undefined) {
                  setZipCodeState(zipcodes.lookup(event.target.value))
                } else {
                  setZipCodeState(undefined)
                }
              }
            }/>
            <p>{zipCodeState?.city}{zipCodeState?.state != undefined ? (",") : ("")} {zipCodeState?.state}</p>
            </div>
            <div>
              <p>What's your Phone Number?</p>
              <PhoneInput
                placeholder="Enter phone number"
                value={phone}
                defaultCountry="US"
                onChange={setPhone}/>
              <button
              onClick={() => console.log({user: {"zip": zipCode, "phone_number": phone}})}
            >Submit</button>
          </div>
          <h1></h1>
        </div>
      </main>
    </>
  )
}